CREATE TABLE CLIENT 
(
	CLIENT_ID CHAR(4) NOT NULL,
	CLIENT_NAME VARCHAR(40) NOT NULL

	CONSTRAINT [PK_CLIENT] PRIMARY KEY (CLIENT_ID)
);
GO

CREATE TABLE [ORDER]
(
	ORDER_ID INT NOT NULL,
	CLIENT_ID CHAR(4) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	CONSTRAINT [PK_ORDER] PRIMARY KEY (ORDER_ID),
	CONSTRAINT [FK_ORDER_CLIENT] FOREIGN KEY (CLIENT_ID)
		REFERENCES CLIENT (CLIENT_ID)

	);


GO


CREATE TABLE CLIENT_CONTACT
(
	CLIENT_ID CHAR(4) NOT NULL,
	CONTACT_ID INT NOT NULL,
	CONTACT_NAME VARCHAR(40) NOT NULL,
	CONTACT_EMAIL VARCHAR(120),
	CONTACT_PHONE VARCHAR(30),

	CONSTRAINT [PK_CLIENT_CONTACT] PRIMARY KEY (CLIENT_ID, CONTACT_ID),
	CONSTRAINT [FK_CL_CONTACT_CLIENT] FOREIGN KEY (CLIENT_ID)
		REFERENCES CLIENT (CLIENT_ID)

);

GO

CREATE TABLE ORDER_DETAIL
( 
	ORDER_ID INT NOT NULL,
	BILLING_TYPE CHAR(2) NOT NULL,
	CLIENT_ID CHAR(4),
	BILLING_CONTACT_ID INT,
	SHIPPING_CONTACT_ID INT,
	CONSTRAINT [PK_ORDER_DETAIL] PRIMARY KEY (ORDER_ID),
	CONSTRAINT [FK_ORDER_DETAIL] FOREIGN KEY (ORDER_ID)
		REFERENCES [ORDER] (ORDER_ID),
	CONSTRAINT [FK_BILLING_CONTACT] FOREIGN KEY (CLIENT_ID, BILLING_CONTACT_ID)
		REFERENCES CLIENT_CONTACT (CLIENT_ID, CONTACT_ID),
	CONSTRAINT [FK_SHIPPING_CONTACT] FOREIGN KEY (CLIENT_ID, SHIPPING_CONTACT_ID)
		REFERENCES CLIENT_CONTACT (CLIENT_ID, CONTACT_ID)
	)


GO